context:
  version: "1.2.1"

package:
  name: behaveai
  version: ${{ version }}

source:
  git: https://github.com/roaldarbol/BehaveAI
  rev: cc809c7fc28a5b770cec6a9e1dc22208d2d500bd

build:
  number: 5
  noarch: python
  python:
    entry_points:
      - behaveai = behaveai.cli:cli
  script:
    - pip install . --no-deps --no-build-isolation
    - if: unix
      then:
        - mkdir -p "$PREFIX/Menu"
        - cp "$RECIPE_DIR/menu.json" "$PREFIX/Menu/behaveai_menu.json"
        # - cp "$RECIPE_DIR/behaveai.png" "$PREFIX/Menu/behaveai.png" # Wait until we have an icon
    - if: win
      then:
        - if not exist "%PREFIX%\Menu" mkdir "%PREFIX%\Menu"
        - copy "%RECIPE_DIR%\menu.json" "%PREFIX%\Menu\behaveai_menu.json"
        # - copy "%RECIPE_DIR%\behaveai.png" "%PREFIX%\Menu\behaveai.png" # Wait until we have an icon

requirements:
  host:
    - python >=3.9
    - pip
    - hatchling
  run:
    - python >=3.9
    - numpy
    - pillow
    - scipy
    - tqdm
    - ultralytics
    - pyyaml
    - py-opencv
    - pytorch
    - torchvision
    - click

about:
  summary: Animal tracking and behaviour classification using YOLO and motion analysis
  license: AGPL-3.0-or-later
  license_file: LICENSE